fixing layout small issues
croct-tech/plug-js pull request #113
Opened 2022-01-19 16:24 UTC by denis-rossati

## Summary

- [ ] Adding the `linkOpened` event
- [ ] Adjusting trailing space and empty blank space issues

### Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2022-01-19 20:25 UTC, amorimjuliana requested changes

2022-01-19 20:25 UTC, amorimjuliana commented on docs/events.md
> +| ['linkOpened'](#linkOpened)                             | Miscellaneous | No            | Records a opened link.
To keep the code standard, please use `Records a link open.` (similar to the `pageOpened` event).

2022-01-19 20:25 UTC, amorimjuliana commented on docs/events.md
> +| ['linkOpened'](#linkOpened)                             | Miscellaneous | No            | Records a opened link.
Also, can you please add this one right after the `postViewed` event, please? The last three events are more general events, It's better if we can keep them together.

2022-01-19 20:25 UTC, amorimjuliana commented on docs/events.md
> +| `link`   | `string` | Yes      | A valid URL | The link that the user opened
Actually, we support URI here. So the constraint should be "A valid URI".

2022-01-20 13:05 UTC, marcospassos requested changes

2022-01-20 13:05 UTC, marcospassos commented on docs/events.md
> +| ['linkOpened'](#linkOpened)                             | Miscellaneous | No            | Records a link open.
This event records a link opening.

2022-01-20 13:42 UTC, merged