Update goalId suggested length
croct-tech/plug-js pull request #128
Opened 2022-07-01 14:50 UTC by denis-rossati

## Summary

- Since [we are changing the goal completed event](https://github.com/croct-tech/sdk-js/pull/208), I'm doing the correspondent changes in the docs.

### Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-07-04 14:10 UTC, Fryuni submitted a review, later dismissed

2022-07-22 13:57 UTC, Fryuni submitted a review, later dismissed

2022-07-22 23:46 UTC, amorimjuliana requested changes

2022-07-22 23:46 UTC, amorimjuliana commented on docs/events.md
> +| `goalId`   | `string` | Yes      | Between 3 and 100 characters long, containing only letters (A-Z), digits (0-9), and separators (`-`,`_`, `:`) , beginning or ending with letters or digits. | The
```suggestion
| `goalId`   | `string` | Yes      | Between 3 and 100 characters long, containing only letters, digits, and separators (`-`,`_`, `:`), starting and ending with letters or digits. | The ID of the goal.
```

2022-08-22 17:37 UTC, isabia approved these changes

2022-08-24 12:21 UTC, Fryuni approved these changes

2022-08-24 12:49 UTC, merged